apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gateway-deployment.yaml
- gateway-service.yaml
- history-deployment.yaml
- history-service.yaml
- worker-deployment.yaml
- worker-service.yaml
- ingress.yaml
