apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gateway-deployment.yaml
- gateway-service.yaml
- gateway-app-deployment.yaml
- gateway-app-service.yaml
- history-deployment.yaml
- history-service.yaml
- voice-deployment.yaml
- voice-service.yaml
- device-deployment.yaml
- device-service.yaml
- worker-deployment.yaml
- worker-service.yaml
- ingress.yaml
