// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"hello/internal/dao/internal"

	"github.com/gogf/gf/v2/database/gdb"
)

// internalActionDao is internal type for wrapping internal DAO implements.
type internalActionDao = *internal.ActionDao

// actionDao is the data access object for table action.
// You can define custom methods on it to extend its functionality as you wish.
type actionDao struct {
	internalActionDao
}

var (
	// Action is globally public accessible object for table action operations.
	Action = actionDao{
		internal.NewActionDao(),
	}
)

// Fill with you ideas below.
func (dao actionDao) Group() string {
	return resolveDBGroup(context.Background(), "device")
}

func (dao actionDao) Ctx(ctx context.Context) *gdb.Model {
	return domainModel(ctx, "device", dao.Table())
}
