// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalDomainOutboxDao is internal type for wrapping internal DAO implements.
type internalDomainOutboxDao = *internal.DomainOutboxDao

// domainOutboxDao is the data access object for table domain_outbox.
// You can define custom methods on it to extend its functionality as you wish.
type domainOutboxDao struct {
	internalDomainOutboxDao
}

var (
	// DomainOutbox is globally public accessible object for table domain_outbox operations.
	DomainOutbox = domainOutboxDao{
		internal.NewDomainOutboxDao(),
	}
)

// Fill with you ideas below.
