// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"hello/internal/dao/internal"

	"github.com/gogf/gf/v2/database/gdb"
)

// internalEventDao is internal type for wrapping internal DAO implements.
type internalEventDao = *internal.EventDao

// eventDao is the data access object for table event.
// You can define custom methods on it to extend its functionality as you wish.
type eventDao struct {
	internalEventDao
}

var (
	// Event is globally public accessible object for table event operations.
	Event = eventDao{
		internal.NewEventDao(),
	}
)

// Fill with you ideas below.
func (dao eventDao) Group() string {
	return resolveDBGroup(context.Background(), "device")
}

func (dao eventDao) Ctx(ctx context.Context) *gdb.Model {
	return domainModel(ctx, "device", dao.Table())
}
