// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalHistoryDao is internal type for wrapping internal DAO implements.
type internalHistoryDao = *internal.HistoryDao

// historyDao is the data access object for table history.
// You can define custom methods on it to extend its functionality as you wish.
type historyDao struct {
	internalHistoryDao
}

var (
	// History is globally public accessible object for table history operations.
	History = historyDao{
		internal.NewHistoryDao(),
	}
)

// Fill with you ideas below.
