// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"hello/internal/dao/internal"

	"github.com/gogf/gf/v2/database/gdb"
)

// internalHistoryDao is internal type for wrapping internal DAO implements.
type internalHistoryDao = *internal.HistoryDao

// historyDao is the data access object for table history.
// You can define custom methods on it to extend its functionality as you wish.
type historyDao struct {
	internalHistoryDao
}

var (
	// History is globally public accessible object for table history operations.
	History = historyDao{
		internal.NewHistoryDao(),
	}
)

// Fill with you ideas below.
func (dao historyDao) Group() string {
	return resolveDBGroup(context.Background(), "history")
}

func (dao historyDao) Ctx(ctx context.Context) *gdb.Model {
	return domainModel(ctx, "history", dao.Table())
}

func (dao historyDao) ReadCtx(ctx context.Context) *gdb.Model {
	return domainReadModel(ctx, dao.Table(), "history_ro", "history", "default")
}

func (dao historyDao) WriteCtx(ctx context.Context) *gdb.Model {
	return domainModel(ctx, "history", dao.Table())
}
