// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalIntentionDao is internal type for wrapping internal DAO implements.
type internalIntentionDao = *internal.IntentionDao

// intentionDao is the data access object for table intention.
// You can define custom methods on it to extend its functionality as you wish.
type intentionDao struct {
	internalIntentionDao
}

var (
	// Intention is globally public accessible object for table intention operations.
	Intention = intentionDao{
		internal.NewIntentionDao(),
	}
)

// Fill with you ideas below.
