// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalQaDao is internal type for wrapping internal DAO implements.
type internalQaDao = *internal.QaDao

// qaDao is the data access object for table qa.
// You can define custom methods on it to extend its functionality as you wish.
type qaDao struct {
	internalQaDao
}

var (
	// Qa is globally public accessible object for table qa operations.
	Qa = qaDao{
		internal.NewQaDao(),
	}
)

// Fill with you ideas below.
