// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalSuggestDao is internal type for wrapping internal DAO implements.
type internalSuggestDao = *internal.SuggestDao

// suggestDao is the data access object for table suggest.
// You can define custom methods on it to extend its functionality as you wish.
type suggestDao struct {
	internalSuggestDao
}

var (
	// Suggest is globally public accessible object for table suggest operations.
	Suggest = suggestDao{
		internal.NewSuggestDao(),
	}
)

// Fill with you ideas below.
