// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"hello/internal/dao/internal"

	"github.com/gogf/gf/v2/database/gdb"
)

// internalSuggestDao is internal type for wrapping internal DAO implements.
type internalSuggestDao = *internal.SuggestDao

// suggestDao is the data access object for table suggest.
// You can define custom methods on it to extend its functionality as you wish.
type suggestDao struct {
	internalSuggestDao
}

var (
	// Suggest is globally public accessible object for table suggest operations.
	Suggest = suggestDao{
		internal.NewSuggestDao(),
	}
)

// Fill with you ideas below.
func (dao suggestDao) Group() string {
	return resolveDBGroup(context.Background(), "voice")
}

func (dao suggestDao) Ctx(ctx context.Context) *gdb.Model {
	return domainModel(ctx, "voice", dao.Table())
}
