// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

type internalUcgPostVoteDao = *internal.UcgPostVoteDao

type ucgPostVoteDao struct {
	internalUcgPostVoteDao
}

var (
	UcgPostVote = ucgPostVoteDao{
		internal.NewUcgPostVoteDao(),
	}
)
