// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

type internalUcgMediaBlobDao = *internal.UcgMediaBlobDao

type ucgMediaBlobDao struct {
	internalUcgMediaBlobDao
}

var (
	UcgMediaBlob = ucgMediaBlobDao{
		internal.NewUcgMediaBlobDao(),
	}
)
