// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

type internalUcgChatMessageDao = *internal.UcgChatMessageDao

type ucgChatMessageDao struct {
	internalUcgChatMessageDao
}

var (
	UcgChatMessage = ucgChatMessageDao{
		internal.NewUcgChatMessageDao(),
	}
)
