// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

type internalUcgPushDeviceDao = *internal.UcgPushDeviceDao

type ucgPushDeviceDao struct {
	internalUcgPushDeviceDao
}

var (
	UcgPushDevice = ucgPushDeviceDao{
		internal.NewUcgPushDeviceDao(),
	}
)
