// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalUcgFollowDao is internal type for wrapping internal DAO implements.
type internalUcgFollowDao = *internal.UcgFollowDao

// ucgFollowDao is the data access object for table ucg_follow.
// You can define custom methods on it to extend its functionality as you wish.
type ucgFollowDao struct {
	internalUcgFollowDao
}

var (
	// UcgFollow is globally public accessible object for table ucg_follow operations.
	UcgFollow = ucgFollowDao{
		internal.NewUcgFollowDao(),
	}
)

// Fill with you ideas below.
