// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

type internalUcgChatMessageOutboxDao = *internal.UcgChatMessageOutboxDao

type ucgChatMessageOutboxDao struct {
	internalUcgChatMessageOutboxDao
}

var (
	UcgChatMessageOutbox = ucgChatMessageOutboxDao{
		internal.NewUcgChatMessageOutboxDao(),
	}
)
