// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalUcgPostRecommendDao is internal type for wrapping internal DAO implements.
type internalUcgPostRecommendDao = *internal.UcgPostRecommendDao

// ucgPostRecommendDao is the data access object for table ucg_post_recommend.
// You can define custom methods on it to extend its functionality as you wish.
type ucgPostRecommendDao struct {
	internalUcgPostRecommendDao
}

var (
	// UcgPostRecommend is globally public accessible object for table ucg_post_recommend operations.
	UcgPostRecommend = ucgPostRecommendDao{
		internal.NewUcgPostRecommendDao(),
	}
)

// Fill with you ideas below.
