// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalUcgPostLikeDao is internal type for wrapping internal DAO implements.
type internalUcgPostLikeDao = *internal.UcgPostLikeDao

// ucgPostLikeDao is the data access object for table ucg_post_like.
// You can define custom methods on it to extend its functionality as you wish.
type ucgPostLikeDao struct {
	internalUcgPostLikeDao
}

var (
	// UcgPostLike is globally public accessible object for table ucg_post_like operations.
	UcgPostLike = ucgPostLikeDao{
		internal.NewUcgPostLikeDao(),
	}
)

// Fill with you ideas below.
