// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalUcgProfileDao is internal type for wrapping internal DAO implements.
type internalUcgProfileDao = *internal.UcgProfileDao

// ucgProfileDao is the data access object for table ucg_profile.
// You can define custom methods on it to extend its functionality as you wish.
type ucgProfileDao struct {
	internalUcgProfileDao
}

var (
	// UcgProfile is globally public accessible object for table ucg_profile operations.
	UcgProfile = ucgProfileDao{
		internal.NewUcgProfileDao(),
	}
)

// Fill with you ideas below.
