// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalUcgPostDao is internal type for wrapping internal DAO implements.
type internalUcgPostDao = *internal.UcgPostDao

// ucgPostDao is the data access object for table ucg_post.
// You can define custom methods on it to extend its functionality as you wish.
type ucgPostDao struct {
	internalUcgPostDao
}

var (
	// UcgPost is globally public accessible object for table ucg_post operations.
	UcgPost = ucgPostDao{
		internal.NewUcgPostDao(),
	}
)

// Fill with you ideas below.
