// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalUcgAiConfigDao is internal type for wrapping internal DAO implements.
type internalUcgAiConfigDao = *internal.UcgAiConfigDao

// ucgAiConfigDao is the data access object for table ucg_ai_config.
// You can define custom methods on it to extend its functionality as you wish.
type ucgAiConfigDao struct {
	internalUcgAiConfigDao
}

var (
	// UcgAiConfig is globally public accessible object for table ucg_ai_config operations.
	UcgAiConfig = ucgAiConfigDao{
		internal.NewUcgAiConfigDao(),
	}
)

// Fill with you ideas below.
