// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalUcgConversationMemberDao is internal type for wrapping internal DAO implements.
type internalUcgConversationMemberDao = *internal.UcgConversationMemberDao

// ucgConversationMemberDao is the data access object for table ucg_conversation_member.
// You can define custom methods on it to extend its functionality as you wish.
type ucgConversationMemberDao struct {
	internalUcgConversationMemberDao
}

var (
	// UcgConversationMember is globally public accessible object for table ucg_conversation_member operations.
	UcgConversationMember = ucgConversationMemberDao{
		internal.NewUcgConversationMemberDao(),
	}
)

// Fill with you ideas below.
