// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

type internalUcgProfileAuditJobDao = *internal.UcgProfileAuditJobDao

type ucgProfileAuditJobDao struct {
	internalUcgProfileAuditJobDao
}

var (
	UcgProfileAuditJob = ucgProfileAuditJobDao{
		internal.NewUcgProfileAuditJobDao(),
	}
)
