// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

type internalUcgNotificationDao = *internal.UcgNotificationDao

type ucgNotificationDao struct {
	internalUcgNotificationDao
}

var (
	UcgNotification = ucgNotificationDao{
		internal.NewUcgNotificationDao(),
	}
)
