// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalUcgConversationDao is internal type for wrapping internal DAO implements.
type internalUcgConversationDao = *internal.UcgConversationDao

// ucgConversationDao is the data access object for table ucg_conversation.
// You can define custom methods on it to extend its functionality as you wish.
type ucgConversationDao struct {
	internalUcgConversationDao
}

var (
	// UcgConversation is globally public accessible object for table ucg_conversation operations.
	UcgConversation = ucgConversationDao{
		internal.NewUcgConversationDao(),
	}
)

// Fill with you ideas below.
