// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalUcgPostMediaDao is internal type for wrapping internal DAO implements.
type internalUcgPostMediaDao = *internal.UcgPostMediaDao

// ucgPostMediaDao is the data access object for table ucg_post_media.
// You can define custom methods on it to extend its functionality as you wish.
type ucgPostMediaDao struct {
	internalUcgPostMediaDao
}

var (
	// UcgPostMedia is globally public accessible object for table ucg_post_media operations.
	UcgPostMedia = ucgPostMediaDao{
		internal.NewUcgPostMediaDao(),
	}
)

// Fill with you ideas below.
