// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalUcgMediaUploadDao is internal type for wrapping internal DAO implements.
type internalUcgMediaUploadDao = *internal.UcgMediaUploadDao

// ucgMediaUploadDao is the data access object for table ucg_media_upload.
// You can define custom methods on it to extend its functionality as you wish.
type ucgMediaUploadDao struct {
	internalUcgMediaUploadDao
}

var (
	// UcgMediaUpload is globally public accessible object for table ucg_media_upload operations.
	UcgMediaUpload = ucgMediaUploadDao{
		internal.NewUcgMediaUploadDao(),
	}
)

// Fill with you ideas below.
