// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"hello/internal/dao/internal"
)

// internalUcgPostCommentDao is internal type for wrapping internal DAO implements.
type internalUcgPostCommentDao = *internal.UcgPostCommentDao

// ucgPostCommentDao is the data access object for table ucg_post_comment.
// You can define custom methods on it to extend its functionality as you wish.
type ucgPostCommentDao struct {
	internalUcgPostCommentDao
}

var (
	// UcgPostComment is globally public accessible object for table ucg_post_comment operations.
	UcgPostComment = ucgPostCommentDao{
		internal.NewUcgPostCommentDao(),
	}
)

// Fill with you ideas below.
